#include <music.h>

int buzzPin = GPIO_NUM_16;
int channel = 0;

int p1[][2] = //Um compasso por linha
{
{N_E4, SEMICOLCHEIA}, {N_E4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_E4, 2*SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, 
{N_E4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_G4, SEMINIMA+COLCHEIA},  {N_G3, SEMINIMA+COLCHEIA},

{N_C4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA},
{N_G3, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA},
{N_D3, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA},

{N_A3, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_B3, 2*SEMICOLCHEIA}, {N_BB3, SEMICOLCHEIA},
{N_A3, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA},

{N_G3, COLCHEIA}, {N_E4, COLCHEIA}, {N_G4, COLCHEIA}, {N_A4, COLCHEIA},
{N_F4, SEMICOLCHEIA}, {N_G4, 2*SEMICOLCHEIA}, {N_E4, COLCHEIA}, {N_C4, SEMICOLCHEIA},
{N_D4, SEMICOLCHEIA}, {N_B3, SEMICOLCHEIA + FUSA},

//REPETE ACIMA
{N_C4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA},
{N_G3, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA},
{N_D3, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA},

{N_A3, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_B3, 2*SEMICOLCHEIA}, {N_BB3, SEMICOLCHEIA},
{N_A3, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA},

{N_G3, COLCHEIA}, {N_E4, COLCHEIA}, {N_G4, COLCHEIA}, {N_A4, COLCHEIA},
{N_F4, SEMICOLCHEIA}, {N_G4, 2*SEMICOLCHEIA}, {N_E4, COLCHEIA}, {N_C4, SEMICOLCHEIA},
{N_D4, SEMICOLCHEIA}, {N_B3, SEMICOLCHEIA + FUSA},

//---------------------------------------
{PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_G4, SEMICOLCHEIA}, {N_GB4, SEMICOLCHEIA}, 
{N_F4, SEMICOLCHEIA}, {N_DS4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_E4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {N_GS3, SEMICOLCHEIA}, {N_A3, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {N_A3, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, {N_D4, SEMICOLCHEIA}, 

{PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_G4, SEMICOLCHEIA}, {N_GB4, SEMICOLCHEIA}, 
{N_F4, SEMICOLCHEIA}, {N_DS4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_E4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {N_C5, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, 
{N_C5, SEMICOLCHEIA}, {N_C5, SEMICOLCHEIA}, {PAUSA, 3*SEMICOLCHEIA},

{PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_G4, SEMICOLCHEIA}, {N_GB4, SEMICOLCHEIA}, 
{N_F4, SEMICOLCHEIA}, {N_DS4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_E4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {N_GS3, SEMICOLCHEIA}, {N_A3, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {N_A3, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, {N_D4, SEMICOLCHEIA}, 

{PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_DS4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_D4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_C4, SEMINIMA+COLCHEIA}, 

//REPETE ACIMA
{PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_G4, SEMICOLCHEIA}, {N_GB4, SEMICOLCHEIA}, 
{N_F4, SEMICOLCHEIA}, {N_DS4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_E4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {N_GS3, SEMICOLCHEIA}, {N_A3, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {N_A3, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, {N_D4, SEMICOLCHEIA}, 

{PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_G4, SEMICOLCHEIA}, {N_GB4, SEMICOLCHEIA}, 
{N_F4, SEMICOLCHEIA}, {N_DS4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_E4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {N_C5, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, 
{N_C5, SEMICOLCHEIA}, {N_C5, SEMICOLCHEIA}, {PAUSA, 3*SEMICOLCHEIA},

{PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_G4, SEMICOLCHEIA}, {N_GB4, SEMICOLCHEIA}, 
{N_F4, SEMICOLCHEIA}, {N_DS4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_E4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {N_GS3, SEMICOLCHEIA}, {N_A3, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {N_A3, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, {N_D4, SEMICOLCHEIA}, 

{PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_DS4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_D4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_C4, SEMINIMA+COLCHEIA}, 

//--------------------------------------
{N_C4, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_C4, 2*SEMICOLCHEIA}, 
{N_C4, SEMICOLCHEIA}, {N_D4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_E4, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {N_A3, SEMICOLCHEIA}, {N_G3, COLCHEIA}, {PAUSA, COLCHEIA}, 

{N_C4, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_C4, 2*SEMICOLCHEIA}, 
{N_C4, SEMICOLCHEIA}, {N_D4, SEMICOLCHEIA}, {N_E4, SEMICOLCHEIA}, {PAUSA, MINIMA}, 

{N_C4, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_C4, 2*SEMICOLCHEIA}, 
{N_C4, SEMICOLCHEIA}, {N_D4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_E4, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, 
{PAUSA, SEMICOLCHEIA}, {N_A3, SEMICOLCHEIA}, {N_G3, COLCHEIA}, {PAUSA, COLCHEIA}, 

{N_E4, SEMICOLCHEIA}, {N_E4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_E4, 2*SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, 
{N_E4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_G4, SEMINIMA+COLCHEIA},  {N_G3, SEMINIMA+COLCHEIA},

{N_E4, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_G3, SEMICOLCHEIA+COLCHEIA}, 
{N_GS3, COLCHEIA}, {N_A3, SEMICOLCHEIA}, {N_F4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_F4, SEMICOLCHEIA},
{N_A3, COLCHEIA}, {PAUSA, COLCHEIA}, 

{N_B3, COLCHEIA}, {N_A4, COLCHEIA}, {N_A4, COLCHEIA}, {N_A4, COLCHEIA}, {N_G4, COLCHEIA}, 
{N_F4, COLCHEIA}, {N_E4, SEMICOLCHEIA}, {N_C4, COLCHEIA}, {N_A3, SEMICOLCHEIA}, {N_G3, COLCHEIA}, 
{PAUSA, COLCHEIA}, 

{N_E4, SEMICOLCHEIA}, {N_C4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_G3, SEMICOLCHEIA+COLCHEIA}, 
{N_GS3, COLCHEIA}, {N_A3, SEMICOLCHEIA}, {N_F4, SEMICOLCHEIA}, {PAUSA, SEMICOLCHEIA}, {N_F4, SEMICOLCHEIA},
{N_A3, COLCHEIA}, {PAUSA, COLCHEIA}, 

{N_B3, COLCHEIA}, {N_F4, COLCHEIA}, {N_F4, COLCHEIA}, {N_F4, COLCHEIA}, {N_E4, COLCHEIA}, 
{N_D4, COLCHEIA}, {N_C4, MINIMA}, {PAUSA, MINIMA}, 

{-1, -1}
};

int p2[][2] = //Um compasso por linha
{
{(N_A4), COLCHEIA}, 
{N_BB4, COLCHEIA}, 
{N_B4, COLCHEIA}, 
{N_C5, SEMINIMA}, 
{-1, -1}
};

int p3[][2] = //Um compasso por linha
{
{(N_EB4), SEMICOLCHEIA}, 
{N_EB4, SEMICOLCHEIA}, 
{N_EB4, SEMICOLCHEIA}, 
{N_EB4, MINIMA}, 

{N_B3, MINIMA}, 
{N_DB4, SEMICOLCHEIA}, 
{N_EB4, MINIMA}, 
{N_DB4, SEMICOLCHEIA},
{N_EB4, SEMIBREVE}, 
{-1, -1}
};

int p4[][2] = //Um compasso por linha
{
{(N_C4), SEMINIMA}, 
{N_E4, SEMINIMA}, 
{N_C4, MINIMA}, 
{-1, -1}
};

//Game of thrones
int p5[][2] = //Um compasso por linha
{
{N_G4, SEMINIMA}, {N_C3, SEMINIMA}, {N_EB4, COLCHEIA}, {N_F4, COLCHEIA}, 
{N_G4, SEMINIMA}, {N_C3, SEMINIMA}, {N_EB4, COLCHEIA}, {N_F4, COLCHEIA}, 
{N_G4, SEMINIMA}, {N_C3, SEMINIMA}, {N_EB4, COLCHEIA}, {N_F4, COLCHEIA}, 
{N_G4, SEMINIMA}, {N_C3, SEMINIMA}, {N_EB4, COLCHEIA}, {N_F4, COLCHEIA}, 

{N_G4, SEMINIMA}, {N_C3, SEMINIMA}, {N_E4, COLCHEIA}, {N_F4, COLCHEIA}, 
{N_G4, SEMINIMA}, {N_C3, SEMINIMA}, {N_E4, COLCHEIA}, {N_F4, COLCHEIA}, 
{N_G4, SEMINIMA}, {N_C3, SEMINIMA}, {N_E4, COLCHEIA}, {N_F4, COLCHEIA}, 
{N_G4, SEMINIMA}, {N_C3, SEMINIMA}, {N_E4, COLCHEIA}, {N_F4, COLCHEIA}, 

{N_G4, MINIMA}, {N_G4, SEMINIMA},

{N_C4, MINIMA}, {N_C4, SEMINIMA},

{N_EB4, COLCHEIA}, {N_F4, COLCHEIA}, {N_G4, MINIMA},

{N_C4, MINIMA}, {N_EB4, COLCHEIA}, {N_F4, COLCHEIA},

{N_D4, SEMINIMA}, {N_G3, SEMINIMA}, {N_BB3, COLCHEIA}, {N_C4, COLCHEIA}, 

{N_D4, SEMINIMA}, {N_G3, SEMINIMA}, {N_BB3, COLCHEIA}, {N_C4, COLCHEIA}, 

{N_D4, SEMINIMA}, {N_G3, SEMINIMA}, {N_BB3, COLCHEIA}, {N_C4, COLCHEIA}, 

{N_D4, SEMINIMA}, {N_G4, SEMINIMA}, {N_BB4, SEMINIMA},

{N_F4, MINIMA}, {N_F4, SEMINIMA},

{N_BB3, MINIMA}, {N_BB3, SEMINIMA},

{N_EB4, COLCHEIA}, {N_D4, COLCHEIA}, {N_F4, MINIMA},

{-1, -1}
};

//Song of storms
int p6[][2] = //Um compasso por linha
{
{N_D4, COLCHEIA}, {N_F4, COLCHEIA}, {N_D5, MINIMA},

{N_D4, COLCHEIA}, {N_F4, COLCHEIA}, {N_D5, MINIMA},

{N_E5, SEMINIMA + COLCHEIA}, {N_F5, COLCHEIA}, {N_E5, COLCHEIA}, {N_F5, COLCHEIA},

{N_E5, COLCHEIA}, {N_C5, COLCHEIA}, {N_A4, SEMINIMA}, {PAUSA, SEMINIMA},

//------------------------------
{N_A4, SEMINIMA}, {N_D4, SEMINIMA}, {N_F4, COLCHEIA}, {N_G4, COLCHEIA},

{N_A4, MINIMA + SEMINIMA}, 

{N_A4, SEMINIMA}, {N_D4, SEMINIMA}, {N_F4, COLCHEIA}, {N_G4, COLCHEIA},

{N_E4, MINIMA + SEMINIMA}, 

//------------------------------
{N_D4, COLCHEIA}, {N_F4, COLCHEIA}, {N_D5, MINIMA},

{N_D4, COLCHEIA}, {N_F4, COLCHEIA}, {N_D5, MINIMA},

{N_E5, SEMINIMA + COLCHEIA}, {N_F5, COLCHEIA}, {N_E5, COLCHEIA}, {N_F5, COLCHEIA},

{N_E5, COLCHEIA}, {N_C5, COLCHEIA}, {N_A4, SEMINIMA}, {PAUSA, SEMINIMA},

//------------------------------
{N_A4, SEMINIMA}, {N_D4, SEMINIMA}, {N_F4, COLCHEIA}, {N_G4, COLCHEIA},

{N_A4, MINIMA}, {N_A4, SEMINIMA}, 

{N_D4, 2*(MINIMA + SEMINIMA)},

{-1, -1}
};

void initializeBuzzer()
{
    pinMode(buzzPin, OUTPUT);
    ledcAttachPin(buzzPin, 0);
    ledcSetup(channel, 2000, 8);
}

void play(int partitura[][2])
{
    int i = 0;
    while (true)
    {
        if (partitura[i][0] == -1)
        {
            break;
        }
        ledcWriteTone(channel, partitura[i][0]);
        delay(partitura[i][1]);
        i++;
    }
    ledcWriteTone(channel, 0);
}

void playInitSong(){
    play(p6);
}

void playAcessSong(){
    play(p3);
}

void playDeniedSong(){
    play(p4);
}