#ifndef PAGE_H
#define PAGE_H

#include <Arduino.h>

String page_old = 
"HTTP/1.1 200 OK\n"
"Content-type:text/html\n"
"\n"
"Click <a href=\"/H\">here</a> to turn the LED on pin 2 on.<br>\n"
"Click <a href=\"/L\">here</a> to turn the LED on pin 2 off.<br>\n"
"<button type=\"button\">Click Me!</button>"
"\n";

String page_controller = "<!doctype html>\n\r"
"\n\r"
"<html lang=\"en\">\r\n"
"<head>\r\n"
"  <meta charset=\"utf-8\">\r\n"
"  <title>ESP32 - Curso introdutório</title>\r\n"
"  <meta name=\"ESP32\" content=\"ESP32 Teste\">\r\n"
"</head>\r\n"
"\r\n"
"<style>\r\n"
"  body {"
"    background-image: url(\"https://i.imgur.com/lAJhivU.png\");"
"    background-repeat: repeat;"
"  }"
"  h1 {\r\n"
"    font-family: \'Source Sans Pro\', sans-serif;\r\n"
"    text-align-last: center;\r\n"
"    width: 100%;\r\n"
"  }\r\n"
"  p{\r\n"
"    text-align-last: center;\r\n"
"    width: 100%;\r\n"
"  }\r\n"
"  .firstDiv {\r\n"
"    width: 500px;\r\n"
"    position: fixed;\r\n"
"    top: 70%;\r\n"
"    left: 50%;\r\n"
"    transform: translate(-50%, -50%);\r\n"
"    background-color: #F1F1F1;\r\n"
"    border-radius: 10px;"
" }\r\n"
"  .imgDiv {\r\n"
"    width: 500px;\r\n"
"    position: fixed;\r\n"
"    top: 30%;\r\n"
"    left: 50%;\r\n"
"    transform: translate(-30%, -40%);\r\n"
" }\r\n"
"    button {"
"    background-color: #4CAF50; /* Green */"
"    border: none;"
"    color: white;"
"    padding: 15px 32px;"
"    text-align: center;"
"    text-decoration: none;"
"    display: inline-block;"
"    font-size: 16px;"
"    border-radius: 10px;"
"    }"
"</style>\r\n"
"\r\n"
"<body>\r\n"
"  <script>\r\n"
"    window.addEventListener(\"gamepadconnected\", (event) => {\r\n"
"       console.log(\"A gamepad connected:\");\r\n"
"       console.log(event.gamepad);\r\n"
"       var intervalID = setInterval(function(){gameLoop()}, 100);\r\n"
"    });\r\n"
"    window.addEventListener(\"gamepaddisconnected\", (event) => {\r\n"
"       console.log(\"A gamepad disconnected:\");\r\n"
"       console.log(event.gamepad);\r\n"
"    });\r\n"
"    function gameLoop() {\r\n"
"      var gamepad = navigator.getGamepads()[0];\r\n"
"       if(gamepad.buttons[0].value > 0 || gamepad.buttons[0].pressed == true) {\r\n"
"           LedOn();\r\n"
"       };\r\n"
"       if(gamepad.buttons[1].value > 0 || gamepad.buttons[1].pressed == true) {\r\n"
"           LedOff();\r\n"
"       };\r\n"
"    }"
"    function LedOn() {\r\n"
"      var xhttp = new XMLHttpRequest();\r\n"
"      xhttp.open(\"GET\", \"/H\", true);\r\n"
"      xhttp.setRequestHeader(\"Content-type\", \"text/html\");\r\n"
"      xhttp.send(\"Sem dados, somente o get\");\r\n"
"    }\r\n"
"    function LedOff() {\r\n"
"      var xhttp = new XMLHttpRequest();\r\n"
"      xhttp.open(\"GET\", \"/L\", true);\r\n"
"      xhttp.setRequestHeader(\"Content-type\", \"text/html\");\r\n"
"      xhttp.send(\"Sem dados, somente o get\");\r\n"
"    }\r\n"
"  </script>\r\n"
"  <div class=\"imgDiv\">\r\n"
"     <img src=\"https://i.imgur.com/kBRQnHS.png\">"
"  </div>\r\n"
"  <div class=\"firstDiv\">\r\n"
"    <h1>ESP32 - Teste acionamento</h1>\r\n"
"    <p>\r\n"
"      <button style=\"align-self: center;\" onclick=\"LedOn()\">ON</button>\r\n"
"    </p>\r\n"
"    <p>\r\n"
"      <button style=\"align-self: center;\" onclick=\"LedOff()\">OFF</button>\r\n"
"    </p>\r\n"
"    <p id=\"info\"></p>\r\n"
"  </div>\r\n"
"\r\n"
"</body>\r\n"
"</html>\r\n"
"";

String page = "<!doctype html>\n\r"
"\n\r"
"<html lang=\"en\">\r\n"
"<head>\r\n"
"  <meta charset=\"utf-8\">\r\n"
"  <title>ESP32 - Curso introdutório</title>\r\n"
"  <meta name=\"ESP32\" content=\"ESP32 Teste\">\r\n"
"</head>\r\n"
"\r\n"
"<style>\r\n"
"  body {"
"    background-image: url(\"https://i.imgur.com/lAJhivU.png\");"
"    background-repeat: repeat;"
"  }"
"  h1 {\r\n"
"    font-family: \'Source Sans Pro\', sans-serif;\r\n"
"    text-align-last: center;\r\n"
"    width: 100%;\r\n"
"  }\r\n"
"  p{\r\n"
"    text-align-last: center;\r\n"
"    width: 100%;\r\n"
"  }\r\n"
"  .firstDiv {\r\n"
"    width: 500px;\r\n"
"    position: fixed;\r\n"
"    top: 70%;\r\n"
"    left: 50%;\r\n"
"    transform: translate(-50%, -50%);\r\n"
"    background-color: #F1F1F1;\r\n"
"    border-radius: 10px;"
" }\r\n"
"  .imgDiv {\r\n"
"    width: 500px;\r\n"
"    position: fixed;\r\n"
"    top: 30%;\r\n"
"    left: 50%;\r\n"
"    transform: translate(-30%, -40%);\r\n"
" }\r\n"
"    button {"
"    background-color: #4CAF50; /* Green */"
"    border: none;"
"    color: white;"
"    padding: 15px 32px;"
"    text-align: center;"
"    text-decoration: none;"
"    display: inline-block;"
"    font-size: 16px;"
"    border-radius: 10px;"
"    }"
"</style>\r\n"
"\r\n"
"<body>\r\n"
"  <script>\r\n"
"    function LedOn() {\r\n"
"      var xhttp = new XMLHttpRequest();\r\n"
"      xhttp.open(\"GET\", \"/H\", true);\r\n"
"      xhttp.setRequestHeader(\"Content-type\", \"text/html\");\r\n"
"      xhttp.send(\"Sem dados, somente o get\");\r\n"
"    }\r\n"
"    function LedOff() {\r\n"
"      var xhttp = new XMLHttpRequest();\r\n"
"      xhttp.open(\"GET\", \"/L\", true);\r\n"
"      xhttp.setRequestHeader(\"Content-type\", \"text/html\");\r\n"
"      xhttp.send(\"Sem dados, somente o get\");\r\n"
"    }\r\n"
"  </script>\r\n"
"  <div class=\"imgDiv\">\r\n"
"     <img src=\"https://i.imgur.com/kBRQnHS.png\">"
"  </div>\r\n"
"  <div class=\"firstDiv\">\r\n"
"    <h1>ESP32 - Teste acionamento</h1>\r\n"
"    <p>\r\n"
"      <button style=\"align-self: center;\" onclick=\"LedOn()\">ON</button>\r\n"
"    </p>\r\n"
"    <p>\r\n"
"      <button style=\"align-self: center;\" onclick=\"LedOff()\">OFF</button>\r\n"
"    </p>\r\n"
"    <p id=\"info\"></p>\r\n"
"  </div>\r\n"
"\r\n"
"</body>\r\n"
"</html>\r\n"
"";

#endif